name: ML Code Tests for my-mlops-project
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'databricks-config/**'

env:
  DATABRICKS_HOST: https://dbc-38ce632c-4934.cloud.databricks.com
  NODE_TYPE_ID: i3.xlarge
  DATABRICKS_TOKEN: ${{secrets.STAGING_WORKSPACE_TOKEN}}
  
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Feature store tests bring up a local Spark session, so Java is required.
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r test-requirements.txt
      - name: Run tests with pytest
        run: pytest
  
  integration_test:
    needs: unit_tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Train model
        uses: databricks/run-notebook@v0
        id: train
        with:
          local-notebook-path: notebooks/TrainWithFeatureStore.py
          git-commit: ${{ github.event.pull_request.head.sha || github.sha }}
          git-provider: gitHub
          new-cluster-json: >
            {
              "spark_version": "11.0.x-cpu-ml-scala2.12",
              "node_type_id": "${{ env.NODE_TYPE_ID }}",
              "num_workers": 0,
              "spark_conf": {
                "spark.databricks.cluster.profile": "singleNode",
                "spark.master": "local[*, 4]"
              },
              "custom_tags": {
                "ResourceClass": "SingleNode",
                "clusterSource": "mlops-stack/0.0"
              }
            }
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]
          run-name: my-mlops-project Integration Test
          
          pr-comment-github-token: ${{ secrets.GITHUB_TOKEN }}
